# Generated by Django 3.1 on 2021-12-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20211209_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='state',
            field=models.CharField(default='public', max_length=30),
        ),
    ]
