# Generated by Django 3.1 on 2021-12-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_snippet_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='state',
            field=models.CharField(choices=[('public', 'pb'), ('private', 'prt')], max_length=30),
        ),
    ]
